language: php
php:
  - 7.3
before_script:
  - composer install

script: 
  - ./vendor/bin/phpunit --testsuite allTests
  - ./vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run
cache:
  directories:
    - $HOME/.php-cs-fixer