name: PHP Composer

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        config: phpunit.xml
    - name: Run test suite
      run: vendor/bin/phpunit --testsuite allTests
